FROM mcr.microsoft.com/devcontainers/typescript-node:2-22-bookworm

ARG NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
ARG COREPACK_NPM_REGISTRY=https://registry.npmjs.org/

ENV NPM_CONFIG_REGISTRY="${NPM_CONFIG_REGISTRY}" \
    COREPACK_NPM_REGISTRY="${COREPACK_NPM_REGISTRY}"